### ISSUE TITLE
map starts zoomed out on report cards

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#18]
can you fix with leaflet calls please

**Comment by talltom** [comment]
Hi @mehrdadgit - I suspect this is because the map is defined before the map card is loaded, thus breaking Leaflet's sizing/rendering. Leaflet is very fussy about having height/width of container set at load time (in our instance they may not be set yet as the map card is not rendered). Is it possible to add a map.invalidateSize() call with a timeout when the map card is loaded?

See the answer here for an example: https://stackoverflow.com/questions/24412325/resizing-a-leaflet-map-on-container-resize
